<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="paraleltesting.java"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="6.183">
    <properties></properties>

            <testcase
                name="invalidCredentials"
                time="6.183"
                classname="Class3.ParallelTesting">

            <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Invalid credential] but found [Invalid credentials]">
                <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [Invalid credential] but found [Invalid credentials]
                org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)Class3.ParallelTesting.invalidCredentials(ParallelTesting.java:61)java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)java.base/java.lang.reflect.Method.invoke(Method.java:577)org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </failure>
    </testcase>


</testsuite>
